version: '3.9'

services:
  web:
    build:
      context: ./ner_api
      dockerfile: Dockerfile
    volumes:
      - ./ner_api:/backend
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
  db:
    image: postgres:latest
    container_name: lanl_api_db_1
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
  frontend:
    restart: always
    command: npm start
    container_name: front
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - web
