# Generated by Django 4.1 on 2022-08-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nermodel',
            name='training_done',
            field=models.BooleanField(default=False),
        ),
    ]
