# Generated by Django 4.1 on 2022-08-23 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run_scripts', '0002_nermodel_training_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nermodel',
            name='training_done',
        ),
    ]
